name: Create and Push Agent TGZ to Main

on:
  push:
    branches:
      - main
    paths:
      - 'apps/agent-ui/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Enable Corepack
        run: |
          corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build and bundle
        run: |
          cd apps/agent-ui
          yarn bundle

      - name: Rename bundle
        run: |
          if stat out/agent-ui*.tgz > /dev/null 2>&1; then
            mv out/agent-ui*.tgz out/agent-ui-${{ github.sha }}.tgz
          else
            echo "Error: No .tgz file found in out/agent-ui/"
            exit 1
          fi
       
      - name: Create a copy with the name 'agent-ui-latest.tgz'
        run: cp out/agent-ui-${{ github.sha }}.tgz out/agent-ui-latest.tgz

      - name: Upload artifact with SHA
        uses: actions/upload-artifact@v4
        with:
          name: agent-ui-${{ github.sha }}.tgz
          path: out/agent-ui-${{ github.sha }}.tgz
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

      - name: Upload artifact 'agent-ui-latest.tgz'
        uses: actions/upload-artifact@v4
        with:
          name: agent-ui-latest.tgz
          path: out/agent-ui-latest.tgz
          if-no-files-found: error
          retention-days: 1
          compression-level: 0